# Generated by Django 2.2.7 on 2019-11-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miasto',
            options={'verbose_name_plural': 'miasta'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'studenci'},
        ),
        migrations.AlterModelOptions(
            name='uczelnia',
            options={'verbose_name_plural': 'uczelnie'},
        ),
        migrations.AlterField(
            model_name='miasto',
            name='kod',
            field=models.CharField(help_text='Wpisz kod pocztowy', max_length=30),
        ),
        migrations.AlterField(
            model_name='miasto',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='miasto'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dochod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='imie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='roks',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='rok studiów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uczelnia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Uczelnia'),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='uczelnia'),
        ),
    ]
